name: Build and upload PDFs

on: 
  push:
    branches: master

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - root_file: My_Life_in_a_Nutshell_-_First_Era
            working_directory: '01 - My Life in a Nutshell - First Era'
          - root_file: Nature_of_Being
            working_directory: '03 - Nature of Being'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run pdfLaTeX on ${{ matrix.root_file }}
      uses: xu-cheng/latex-action@v2
      with:
        # The root LaTeX file to be compiled
        root_file: ${{ matrix.root_file }}.tex
        # The working directory for the LaTeX engine
        working_directory: ${{ matrix.working_directory }}
        # The LaTeX engine to be invoked
        compiler: latexmk
        # Extra arguments to be passed to the LaTeX engine
        args: -pdf -file-line-error -interaction=nonstopmode -shell-escape
        # [Deprecated] Install extra packages by tlmgr
        extra_packages: # optional
        # Install extra packages by apk
        extra_system_packages: "bash py-pygments"
    - name: Upload PDF artifact for ${{ matrix.root_file }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.root_file }}
        path: ${{ matrix.working_directory }}/${{ matrix.root_file }}.pdf
        retention-days: 2

  deploy-pdfs:
    needs: generate-pdfs
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2

      - name: Collect PDF artifacts and create simple index
        run: |
          mkdir -p pdfs
          mv */*.pdf pdfs/
          echo "<!DOCTYPE html>" > pdfs/index.html
          echo "<html><body><ul>" >> pdfs/index.html
          for PDF in pdfs/*.pdf; do PDF=$(basename "${PDF}"); echo "<li><a href=\"${PDF}\">${PDF}</a></li>" >> pdfs/index.html; done
          echo "</ul></body></html>" >> pdfs/index.html

      - name: Touch .nojekyll
        run: |
          touch pdfs/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./pdfs
          force_orphan: true
