name: Build and upload PDF

on: 
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run pdfLaTeX
      uses: xu-cheng/latex-action@1.2.1
      with:
        # The root LaTeX file to be compiled
        root_file: Nature_of_Being.tex
        # The working directory for the LaTeX engine
        working_directory: latex
        # The LaTeX engine to be invoked
        compiler: latexmk
        # Extra arguments to be passed to the LaTeX engine
        args: -pdf -file-line-error -interaction=nonstopmode -shell-escape
        # [Deprecated] Install extra packages by tlmgr
        extra_packages: # optional
        # Install extra packages by apk
        extra_system_packages: # optional
    - name: Pull out PDF artifact
      run: |
        mkdir -p pdf
        mv latex/Nature_of_Being.pdf pdf/
    - name: Touch .nojekyll
      run: |
        touch pdf/.nojekyll
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./pdf
      with:
        forceOrphan: true
